// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorial' }],
  servicesSidebar: [{ type: 'autogenerated', dirName: 'intro' }],
};

module.exports = sidebars;
